slalom/urls.py
from django.urls import path 
from .views import LevelListView, DetailLevelView, ListProgressView, TricksListView
from . import views 

app_name = 'slalom'
urlpatterns = [
    #path ('', views.index, name='index'),
    path ('', views.LevelListView.as_view(), name='index'),
    path ('level/<int:pk>/', views.DetailLevelView.as_view(), name='level-detail'),
    #path ('trick/<int:pk>/', views.DetailTrickView.as_view(), name='trick-detail'),
    path ('progress/',views.ListProgressView.as_view(), name='progress'),
    path ('trick/<int:trick_id>/', views.trick_detail, name='trick-detail'),
    path ('tricks/',views.TricksListView.as_view(), name='tricks'),
    path('search/', views.search, name='search-tricks'),
    
    
    

    
    
    
    
]

slalom_tricks/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include 
from users import views as user_views 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register, name='register'),
    path('profile/',user_views.profile, name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('slalom.urls')),
    

    
]

users/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
]

slalom/models.py
from django.db import models
from django.contrib.auth.models import User 
from django.urls import reverse 
from embed_video.fields import EmbedVideoField

    

class Level(models.Model):
    number = models.CharField(max_length=5)

    def __str__(self):
        return self.number

class Trick(models.Model):
    name = models.CharField(max_length=250)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    video1 = EmbedVideoField() 
    video2 = EmbedVideoField() 
    video3 = EmbedVideoField()
    link_video1 = models.CharField(max_length=250, default=1)
    link_video2 = models.CharField(max_length=250, default=2)
    link_video3 = models.CharField(max_length=250, default=3)
    def __str__(self):
        return self.name

class Done(models.Model):
    trick = models.ForeignKey(Trick, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    complete = models.BooleanField(default=False)
    date_completed = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.trick.name
    
    def get_absolute_url(self):
        return reverse('slalom:trick-detail', kwargs={'pk': self.pk})

    
# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user= models.OneToOneField(User,on_delete=models.CASCADE)
    #image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'
# Create your models here.

slalom/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User

class CompleteTrick(forms.ModelForm):
    complete =forms.BooleanField()

    class Meta:
        model = Done 
        fields = ['complete']

users/forms.py
from django import forms 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User 
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User 
        fields = ['username', 'email']

"""
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile 
        fields =['image']
""" 

slalom/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView
from .models import *
from .forms import * 


"""
def index(request):
    levels = Level.objects.all()
    context = {'levels': levels}
    return render(request, 'slalom/index.html', context)

     
    return render(request, 'slalom/index.html')
""" 
@login_required
def trick_detail(request, trick_id):
    trick  = Trick.objects.get(id=trick_id)  
    progress = Done.objects.filter(owner=request.user)  
    edit_id = 0                                         
    
    trick_exists = False         
    for pro in progress:        
        if pro.trick_id == trick.id:    
            trick_exists = True         
            edit_id = pro.id            

    
    if request.method !='POST':     
        if trick_exists:            
            edit_progress = progress.get(id=edit_id)    
            form = CompleteTrick(instance=edit_progress) 
        else:
            form = CompleteTrick() 
    else:
        if trick_exists == False:   
            form = CompleteTrick(data=request.POST) 
            if form.is_valid():
                new_progress = form.save(commit=False)   
                new_progress.trick = trick 
                new_progress.owner = request.user
                new_progress.save()
        else:                                   
            edit_progress = progress.get(id=edit_id)       
            form = CompleteTrick(instance=edit_progress)     
            if form.is_valid:                               
                edit_progress = form.save(commit=False)     
                if edit_progress.complete == True:        
                    edit_progress.complete = False      
                else:
                    edit_progress.complete = True       
                edit_progress.save()  
                form = CompleteTrick(instance=edit_progress)
            return redirect('slalom:progress')


    context ={'trick':trick, 'form':form, 'progress': progress}
    return render(request, 'slalom/trick_detail.html', context)




class LevelListView(ListView):
    model = Level 
    template_name = 'slalom/index.html'
    context_object_name = 'levels'

@login_required
def search(request):
    search = request.GET['searched']
    tricks = Trick.objects.filter(name__icontains=search)
    context = {'tricks': tricks, 'search':search}
    return render(request, 'slalom/search-tricks.html', context)



class DetailLevelView(DetailView):
    model = Level 

    def get_context_data(self,**kwargs):
        context = super(DetailLevelView, self).get_context_data(**kwargs)
        context['tricks'] = Trick.objects.all()
        
        return context 

class ListProgressView(ListView):
    model = Done
    template_name = 'slalom/progress.html'
    def get_context_data(self,**kwargs):
        context = super(ListProgressView, self).get_context_data(**kwargs)
        context['tricks'] = Trick.objects.all()
        context['levels'] = Level.objects.all()
        return context 

class TricksListView(ListView):
    model = Trick
    template_name = 'slalom/tricks.html'
    #context_object_name = 'tricks_all'
    def get_context_data(self,**kwargs):
        context = super(TricksListView, self).get_context_data(**kwargs)
        context['done'] = Done.objects.all()
        context['levels'] = Level.objects.all()
        
        return context 





# Create your views here.

users/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm #ProfileUpdateForm

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Account created for {username}.")
            return redirect('slalom:index')
    else:
        form= UserRegisterForm()
    return render (request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        #p_form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        if u_form.is_valid(): #and p_form.is_valid():
            u_form.save() 
            #p_form.save()
            messages.success(request, f"You account has been updated.")
            return redirect('profile')


    else:
        u_form = UserUpdateForm(instance=request.user)
        #p_form = ProfileUpdateForm(instance=request.user.profile)

    context ={'u_form': u_form}
    return render(request, 'users/profile.html', context)
# Create your views here.

slalom/templates/slalom/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title> Slalom Tricks </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'slalom:index' %}"> Home  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'slalom:tricks' %}"> Tricks </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'slalom:progress' %}"> Progress </a>
              </li>
            </ul>
            
          </div>
        </div>
      </nav>
      <br>
      <div class ="container">
        <div class="btn-group">
          {% if user.is_authenticated %} 
          
          <a href="{% url 'slalom:progress' %}" class="btn btn-outline-secondary" aria-current="page"> Progress </a>

          <a href="{% url 'logout' %}" class="btn btn-outline-secondary" aria-current="page">Log out</a>
          <a href="{% url 'profile' %}" class="btn btn-outline-secondary" aria-current="page"> Profile </a>
  

        
          {% else %}
            <a href="{% url 'login' %}"  class="btn btn-secondary" aria-current="page"> Log in</a>
            <a href="{% url 'register' %}" class="btn btn-secondary" aria-current="page"> Register </a>
            
          {% endif %}

         
        </div>

        

        <br>
        
        {% if messages %} 
            {% for message in messages %} 
            <div class="alert-{{ message.tags }}">
                { { message }}

            </div>
            {% endfor %} 
        {% endif %}
          <br> 
        
        
 

        {% block content%} {% endblock content%}
    </div>
    
    



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

    

slalom/templates/slalom/done_form.html
{% extends "slalom/base.html" %} 
{% block content %}

<form method ="POST" >
    {% csrf_token %} 
    <p> Done  </p>
     {{ form.as_p }}

     <button type="submit"> Save </button>
    
</form>

{% endblock content %} 

slalom/templates/slalom/index.html
{% extends "slalom/base.html" %} 
{% block content %}


<h1 style="text-align:center"> Slalom Tricks</h1>

<h2 style="text-align:center"> Levels </h2>


<div class ="container">
    <div class="d-grid gap-2 col-6 mx-auto">
    {%for level in levels %} 

     <a href="{% url 'slalom:level-detail' level.id %}" class="btn btn-dark"> {{ level }} </a> </li>

    {% endfor %} 
    </div> 
    <br>    
    

    <div class="d-grid gap-3 col-6 mx-auto">
    <form class="row g-3" action="{% url 'slalom:search-tricks' %}" method="GET">
        {% csrf_token %} 
        <input class="form-control"  type="search" placeholder="Search" aria-label="Search" name="searched">
        <button class="btn btn-secondary"  type="submit">Search</button>
    </form>
    </div>


</div>



{% endblock content %}

slalom/templates/slalom/level_detail.html
{% extends "slalom/base.html" %} 
{% block content %}

<a href="{% url 'slalom:index' %}" class="btn btn-secondary" aria-current="page"> Back </a>

<h1> Level {{ level.number }} </h1>

{% for trick in tricks %} 
    {% if trick.level.number == level.number %}
        <p> <a href="{% url 'slalom:trick-detail' trick.id %}" > {{ trick.name }} </p></a>
    {% endif %} 
{% endfor %}


{% endblock content %}

slalom/templates/slalom/progress.html
{% extends "slalom/base.html" %} 
{% load static %}
{% block content %}

</br>
<a href="{% url 'slalom:index' %}" class="btn btn-secondary" aria-current="page"> Back </a>

<h1> Progress <small> {{ user.username }} </small></h1> 
<br>
<div > 
<input type="text" id="myInput" onkeyup="searchTrick()" placeholder="Search for trick.." title="Type in a name">
<input type="text" id="myInput2" onkeyup="searchLevel()" placeholder="Search for level.." title="Type in a name">
</div>
<br> 
    <table id="myTable" class="table table-striped"> 
        <tr> 
            <th>Trick </th>
            <th> Complete </th>
            <th> Level </th>
            <th> Date completed</th>
        </tr>
        {% for object in object_list%}
        {% if object.owner.id == user.id %}
        {% if object.complete == True %}
        <tr>
            <td> <a href="{% url 'slalom:trick-detail' object.trick.id %}" > {{ object.trick }} </a> </td>
            <td> {{ object.complete }} </td>
            <td> {{ object.trick.level }} </td>
            <td> {{ object.date_completed }} </td>
        </tr>
        {% endif %}
        {% endif %}
        {% endfor %}
    </table>

    <p> To do </p>
    <table id="myTable2" class="table table-striped"> 
        <tr> 
            <th>Trick </th>
            <th> Complete </th>
            <th> Level </th>
            <th> Date completed</th>
        </tr>
        {% for object in object_list%}
        {% if object.owner.id == user.id %}
        {% if object.complete == False %}
        <tr>
            <td> <a href="{% url 'slalom:trick-detail' object.trick.id %}" > {{ object.trick }} </a> </td>
            <td> {{ object.complete }} </td>
            <td> {{ object.trick.level }} </td>
            <td> ---- </td>
        </tr>
        {% endif %}
        {% endif %}
        {% endfor %}
    </table>


    <script>
        function searchTrick() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[0];
            if (td) {
            txtValue = td.textContent || td.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
            }       
        }
        }

        function searchLevel() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myInput2");
        filter = input.value.toUpperCase();
        table = document.getElementById("myTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[2];
            if (td) {
            txtValue = td.textContent || td.innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                tr[i].style.display = "";
            } else {
                tr[i].style.display = "none";
            }
            }       
        }
        }
    </script>
    
    



<!--    
<ul>
{% for object in object_list%}
{% if object.owner.id == user.id %}

    
    <li> <span> <strong> {{ object.trick }} </strong></span>  {{ object.complete }} {{ object.date_completed}} </li>
    
{% endif %}
{% endfor %}
</ul>
-->

{% endblock content %}

slalom/templates/slalom/search-tricks.html
{% extends "slalom/base.html" %} 
{% block content %}

<a href="{% url 'slalom:index' %}" class="btn btn-secondary" aria-current="page"> Back </a>
<br>
<h1> Results  </h1>

<ul>

{% for trick in tricks %} 
    <li>
        <a href="{% url 'slalom:trick-detail' trick.id %}" > {{ trick.name }} </a>
    </li> 
{% endfor %}
</ul>


{% endblock content %}

slalom/templates/slalom/trick_detail.html
{% extends "slalom/base.html" %} 
{% load static %}
{% load embed_video_tags %}
{% block content %}
<br>
<a href="{% url 'slalom:level-detail' trick.level.number %}" class="btn btn-secondary" aria-current="page"> Level {{trick.level.number}} </a>

 <h1> {{ trick }}  <small>  level {{ trick.level.number }} </small> </h1>




<form action="{% url 'slalom:trick-detail'  trick.id %}" method='POST'>
    {% csrf_token %} 
    {{ form }}
    <input type="submit" value="Save"> 
    {% if form.complete == True %} 
    <p> complete </p>
    {% endif %}

</form> 


{% video trick.video1 %} 
<p> <a href='{{ trick.link_video1 }}'> Watch on youtube</a> </p>

<a href ="{% static '/videos/Fishforward SlalomTricks.mp4'%}" download> Download</a>

{% video trick.video2 %}
<p> <a href='{{ trick.link_video2 }}'> Watch on youtube</a> </p>

{% video trick.video3 %}
<p> <a href='{{ trick.link_video3 }}'> Watch on youtube</a> </p>

    

{% endblock content %}

slalom/templates/slalom/tricks.html
{% extends "slalom/base.html" %} 
{% load static %} 
{% block content %}
<br>
<a href="{% url 'slalom:index' %}" class="btn btn-secondary" aria-current="page"> Home </a>

 <h1> Tricks </h1>


<table class="table table-striped"> 
    <tr> 
        <th>Trick </th>
        <th> Level </th>
        <th> Completed </th>
    </tr>
    {% for object in object_list %}
    <tr>
        <td> <a href="{% url 'slalom:trick-detail' object.id %}" > {{ object.name }}</a> </td>
        <td> <a href="{% url 'slalom:level-detail' object.level %}"> {{ object.level }}</a> </td>
        <td>  - </td>

        
    </tr>

    {% endfor %}
</table>

{% endblock content %}

users/templates/users/login.html
{% extends "slalom/base.html" %} 
{% block content %}

<form method ="POST" >
    {% csrf_token %} 
    <p> Log in </p>
     {{ form.as_p }}

     <button type="submit"> Log In </button>
     <p> Need an account? <a href="{% url 'register' %}"> Sign Up Now</a></p>

</form>

{% endblock content %} 

users/templates/users/logout.html
{% extends "slalom/base.html" %} 
{% block content %}

<h2> You have been logged out </h2>


{% endblock content %} 

users/templates/users/profile.html
{% extends "slalom/base.html" %} 
{% block content %}

<h1> {{ user.username }} </h1>

<form method ="POST" >
    {% csrf_token %} 
    <p> Edit your profile information</p>
     {{ u_form.as_p }}
     {{ p_form.as_p }}

     <button type="submit"> Update </button>
     
</form>


{% endblock content %} 

users/templates/users/register.html
{% extends "slalom/base.html" %} 
{% block content %}

<form method ="POST" >
    {% csrf_token %} 
    <p> Sign up </p>
     {{ form.as_p }}

     <button type="submit"> Sign Up</button>
     <p> Already have an account? <a href="{% url 'register' %}"></a></p>

</form>

{% endblock content %} 